### ISSUE TITLE
Does not work with fira code

### ISSUE THREAD

**Issue by Leone25** [nulled666/nppqcp#44]
The plugin seem to not work with fira code(https://github.com/tonsky/FiraCode), more specifically when the direct wire option is enabled at boot to activate the "custom merging characters"

help? bug? something?

**Comment by Big--Mike** [comment]
Hi, 

I guess incompatibility...

You can use the mode SC_TECHNOLOGY_DIRECTWRITEDC instead of SC_TECHNOLOGY_DIRECTWRITE. 
Ligatures will stay and the colored lines will be displayed.
But if you're hitting keys, the lines vanish and get visible again if you stop typing. 

This doesn't look pretty. So if someone knows, what to do, an update to support default and Direct Draw mode would be welcome.
